spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8085
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
            - openid
            - profile
            - write
            - read
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:8085
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://msvc-product-backlog
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: sprint-service
          uri: lb://msvc-sprint-backlog
          predicates:
            - Path=/sprint/**
          filters:
            - StripPrefix=1
        - id: task
          uri: lb://msvc-task
          predicates:
            - Path=/task/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: oauth
          uri: lb://msvc-oauth
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
  