
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IP_ADDR:http://127.0.0.1:8085}
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
            - openid
            - profile           
            client-name: client-app
        provider:
          spring:
            issuer-uri: ${IP_ADDR:http://127.0.0.1:8085}
  cloud:
    gateway:
     mvc:
      routes:                
        - id: msvc-task
          uri: lb://msvc-task
          predicates:
            - Path=/mscrumjira/task/**
          filters:
            - StripPrefix=2
        - id: msvc-user
          uri: lb://msvc-user
          predicates:
            - Path=/mscrumjira/user/**
          filters:
            - StripPrefix=2
        - id: msvc-oauth
          uri: lb://msvc-oauth
          predicates:
            - Path=/mscrumjira/msvc-oauth/**
          filters:
            - StripPrefix=2    
        - id: msvc-project
          uri: lb://msvc-project
          predicates:
            - Path=/mscrumjira/project/**
          filters:
            - StripPrefix=2        
              