spring:  
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://msvc-product-backlog
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: sprint-service
          uri: lb://msvc-sprint-backlog
          predicates:
            - Path=/sprint/**
          filters:
            - StripPrefix=1
        - id: task
          uri: lb://msvc-task
          predicates:
            - Path=/task/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: oauth
          uri: lb://msvc-oauth
          predicates:
            - Path=/msvc-oauth/**
          filters:
            - StripPrefix=1        
